### ISSUE TITLE
Installer parameters ignored or how to specify install dir?

### ISSUE THREAD

**Issue by lambdor** [jtcmedia/chocolatey-packages#23]
I'm looking for a way to install and manage multiple Unity versions without visiting the official website everytime. Unfortunately it seems that the Unity chocolatey package always installs to the default install dir (`C:\Program Files\Unity` or the previously used install dir). I also tried specifying the choco `--params` parameter as according to the [official installer documentation](https://docs.unity3d.com/Manual/InstallingUnity.html) it should support setting the install directory.

`choco install unity --version 5.6.1 --params="/D=C:\Program Files\Unity 5.6.1f1"`

**Comment by jtcmedia** [comment]
@lambdor I have added this capability in the latest release, 2017.1.1
