### ISSUE TITLE
Arduino pkg sometimes doesn't install silently

### ISSUE THREAD

**Issue by jtcmedia** [jtcmedia/chocolatey-packages#28]
As discussed in the [comments](https://chocolatey.org/packages/arduino) on the package page, some people are having issues with Arduino not installing silently. This is most likely due to the script using autohotkey which depends on timing. As I have been unable to reproduce the error on my own Windows installation nor on Chocolatey's Windows 2012 R2 Testing VM, perhaps someone who has the issue can submit a PR to correct it.

**Comment by jeromeufc** [comment]
It is not the version of Windows the problem, but the language.

Line 8 of the script you are using:
winTitle = Windows Security ahk_class 32770

But for example in French if I change the line by
winTitle = Sécurité Windows ahk_class 32770

The autohotkey script works.

Sorry for my English, I am French.

**Comment by jtcmedia** [comment]
In your case, it wouldn't work because autohotkey is looking for a window with the title "Windows Security". Your using a french version of Windows which is why you had to change it.

**Comment by jtcmedia** [comment]
package being maintained by @tunisiano187 and migrated to https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/arduino
