### ISSUE TITLE
Chocolatey Installer Broken - GnuPG modern 2.2.12

### ISSUE THREAD

**Issue by asheroto** [jtcmedia/chocolatey-packages#35]
Hey there,

Just tried installing the application using Chocolatey.  It installed, but didn't create any shortcuts, and it doesn't look like it did anything.  I did not receive any errors upon install.

I found "GnuPG" folder in Program Files, but I don't know what executable to run.

Here's a few screenshots:

![image](https://user-images.githubusercontent.com/49938263/63552277-e12aec00-c4fc-11e9-88af-4dfd9ceb662f.png)

![image](https://user-images.githubusercontent.com/49938263/63552225-be98d300-c4fc-11e9-9e01-5b8ec9f71ada.png)

![image](https://user-images.githubusercontent.com/49938263/63552447-41ba2900-c4fd-11e9-9789-c64cd81d61f9.png)

**Comment by jtcmedia** [comment]
I no longer maintain this package, the coreteam has taken it over. See https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1215. You might want to raise an issue there.

**Comment by asheroto** [comment]
Okay.  Just so you know this GitHub repo comes up when you click "Package Source" on https://chocolatey.org/packages/gnupg-modern

**Comment by jtcmedia** [comment]
I think you want this package https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/gnupg
