### ISSUE TITLE
Mark the `gnupg‑modern` package as deprecated

### ISSUE THREAD

**Issue by ExE-Boss** [jtcmedia/chocolatey-packages#36]
See https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1333 for details.

This package has been migrated in #32 and https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1319.

---

/cc @gep13, @majkinetor, @wget

**Comment by jtcmedia** [comment]
Thanks @ExE-Boss for the PR to deprecate it in [chocolatey-coreteampackages](https://github.com/chocolatey-community/chocolatey-coreteampackages), which made more sense to me.
