### ISSUE TITLE
cura-lulzbot download broken

### ISSUE THREAD

**Issue by ad1217** [jtcmedia/chocolatey-packages#38]
LulzBot seems to have taken down their Amazon S3 bucket and moved to GitLab for releases.
New URL: https://gitlab.com/lulzbot3d/cura-le/cura-lulzbot/uploads/b11d5c7871cfd14d5a274c6f3c031457/cura-lulzbot_3.6.21_win32.exe

**Comment by jtcmedia** [comment]
Thanks for bringing this to my attention! A new pkg with a fixed URL has been pushed to Chocolatey.
