### ISSUE TITLE
Prusa Slicer 2.2.0 alpha build completely breaks

### ISSUE THREAD

**Issue by NovaViper** [jtcmedia/chocolatey-packages#39]
Hi, the pre release completely screws up for the Prusa Slicer package, it never extracts the zip correctly (leaving no exe anywhere on the computer).

**Comment by jtcmedia** [comment]
I see the issue. Prusa has only released a 64 bit version for 2.2.0 alpha. It isn't clear, from what I could see, whether they are dropping 32 bit support entirely going forward. In any case, the automated script expected 2 urls, one for 32 bit, one for 64 bit. I have fixed the package and pushed a new one to Chocolatey.

**Comment by NovaViper** [comment]
Thanks for the fix!
