### ISSUE TITLE
(ds4windows) Include binaries in package.

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [jtcmedia/chocolatey-packages#40]
It would be nice if the ds4windows package was made internal and included the zips instead of downloading them. 

The license (MIT) definitely is amicable to being internal, as is the total package size (~8mb). 

I would be happy to provide a PR including AU.

**Comment by jtcmedia** [comment]
I think this was one of the first packages I ever did and didn't know about internal at the time. I can prob do this fairly quickly in the next couple of days but if you want to submit a PR, you're more than welcome.

**Comment by TheCakeIsNaOH** [comment]
Awesome, thanks.
