### ISSUE TITLE
Could you add Linux IL2CPP build support when you get a chance?

### ISSUE THREAD

**Issue by JesseTG** [jtcmedia/chocolatey-packages#43]
Unity can now build IL2CPP-backed Linux binaries, as seen here:

![Screenshot 2020-11-18 185025](https://user-images.githubusercontent.com/1175189/99602194-10196180-29cf-11eb-8159-c1355ac71a11.png)

Would you mind adding a package for this whenever you get a chance? Thank you very much!

**Comment by JesseTG** [comment]
Perfect, thank you very much!

**Comment by jtcmedia** [comment]
No problem!
