### ISSUE TITLE
Create ViGemBus package

### ISSUE THREAD

**Issue by sitiom** [jtcmedia/chocolatey-packages#45]
[ViGemBus](https://github.com/ViGEm/ViGEmBus) is one of the dependencies of DS4Windows. Even though DS4Windows downloads it and installs it for you, it might be good if that was managed by chocolatey.

**Comment by jtcmedia** [comment]
Thanks for the issue. Package has been pushed to Chocolatey and should get approved within the next few weeks. I will updt DS4Windows to depend on it.

**Comment by jtcmedia** [comment]
I'm going to re-open this issue. I didn't fully realize the complexity of this package. ViGemBus 1.17.333, which I created a package for, doesn't run on anything but Windows 10. If I add this package as a dependency of DS4Windows, users using earlier versions of Windows will be locked out of installing upgrades (and the author of DS4Windows has set the minimum version of 1.16.112 for ViGemBus). ViGemBus 1.16.116 runs on earlier versions of Windows but has only a single exe for installation compared to 1.17.333 which has x64 and x86 msi. This means I need a whole different package for this version. I'm going to remove the dependency on this package for DS4Windows for now but you can still install this package, as long as you're running Windows 10.

**Comment by jtcmedia** [comment]
Closing this issue since package was created and DS4Windows is no longer in active development.
