### ISSUE TITLE
`cura-lulzbot` has incorrect checksum 

### ISSUE THREAD

**Issue by ad1217** [jtcmedia/chocolatey-packages#46]
Lulzbot seems to have updated the release file, without changing the filename/version. Changed twice in upstream commits [312e6e69](https://gitlab.com/lulzbot3d/cura-le/release/-/commit/312e6e69bed69446e584af724f6ca784fb6a1f43) and [2132dd9e](https://gitlab.com/lulzbot3d/cura-le/release/-/commit/2132dd9e7d05b710302052275300c69e75f53905). Current hash as of [2132dd9e](https://gitlab.com/lulzbot3d/cura-le/release/-/commit/2132dd9e7d05b710302052275300c69e75f53905) is `fa378ca79ff66b0a92fdad6b394774e8d86d09e893f9f194da51da077ab03b9b`.

**Comment by jtcmedia** [comment]
grrr, I hate it when they do that! Thanks for the issue @ad1217. New package has been pushed.
