### ISSUE TITLE
ZAP fails to install via Azure DevOps Pipeline

### ISSUE THREAD

**Issue by tomaustin700** [jtcmedia/chocolatey-packages#50]
**Describe the bug**
When trying to use choco install zap within an Azure DevOps pipeline the install process hangs indefinitely and the pipeline run has to be manually cancelled. Manually running choco install zap works correctly so this is just limited to Azure DevOps pipelines.

**Expected behavior**
Zap should install correctly

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - Version: 21H1

**Additional context**
I have attached chocolately.log and choco.summary.log which show logs for the installation process

[choco.summary.log](https://github.com/jtcmedia/chocolatey-packages/files/7410154/choco.summary.log)
[chocolatey.log](https://github.com/jtcmedia/chocolatey-packages/files/7410155/chocolatey.log)

**Comment by jtcmedia** [comment]
This is most likely a timing issue; especially since you say it installs fine manually. I don't see any errors in the logs you posted other than it not finishing. You can try playing around with the `--timeout` option for `choco install` perhaps or give it more time in your Pipeline?

**Comment by tomaustin700** [comment]
What's weird is that it seems that something pipeline related causes choco install to hang, once the pipeline is cancelled the ZAP install completes.

**Comment by jtcmedia** [comment]
Could it be related to this issue? https://github.com/chocolatey/choco/issues/1871
