### ISSUE TITLE
Update KiCad link

### ISSUE THREAD

**Issue by ferdymercury** [jtcmedia/chocolatey-packages#51]
Please update on https://gist.github.com/8abc37a8c3b020ffdd9704a810331790/d7565e0a7c38f5cc0a84f64b1e5ab2b14145b2dd https://gist.github.com/jtcmedia/8abc37a8c3b020ffdd9704a810331790/0a2e144e7e636ff35eddcc414d833e15f80fbac2 https://gist.github.com/8abc37a8c3b020ffdd9704a810331790/b766d472a16bf543f3b40247299d98e57c076f3e the discontinued KiCad link to the official one (kicad.org)

See https://forum.kicad.info/t/warning-avoid-all-links-to-kicad-pcb-org-use-kicad-org/31521/

**Comment by jtcmedia** [comment]
This was already done, see https://github.com/jtcmedia/chocolatey-packages/commit/97d44451002d7edec4db7e5e7071afd8470deb87#diff-db56b9c3e2c79f93d78cae6dc74cee748d44324c1a39c9064af8e53785e8cd3e. It isn't reflected on the Chocolatey site yet because the latest version was released before this change.
