### ISSUE TITLE
new ViGEmBus version is available

### ISSUE THREAD

**Issue by soredake** [jtcmedia/chocolatey-packages#60]
**Describe the bug**
There is new vigembus version available https://github.com/ViGEm/ViGEmBus/releases/tag/v1.18.367.0

**Expected behavior**
Have new version packaged.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 21H2

**Additional context**

**Comment by jtcmedia** [comment]
I no longer wish to maintain this package. If you wish to take over maintenance, contact Chocolatey admins here: [https://community.chocolatey.org/packages/vigembus/1.17.333/ContactAdmins](https://community.chocolatey.org/packages/vigembus/1.17.333/ContactAdmins). See [https://github.com/chocolatey-community/chocolatey-package-requests/issues/1341](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1341)
