### ISSUE TITLE
[keepass-plugin-keepassnatmsg] Outdated

### ISSUE THREAD

**Issue by brogers5** [jtcmedia/chocolatey-packages#68]
**Describe the bug**
[v2.0.16](https://github.com/smorks/keepassnatmsg/releases/tag/v2.0.16) has been available for at least 2 days, but a new package has not yet been pushed to the Community Repository.

The update script started to fail for this package as of [this AU run](https://gist.github.com/jtcmedia/8abc37a8c3b020ffdd9704a810331790/c643ed77398c8cc90f71c689627195f353350991#keepass-plugin-keepassnatmsg).

**Expected behavior**
`keepass-plugin-keepassnatmsg` package should update without issues.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by jtcmedia** [comment]
Thanks for letting me know @brogers5 . New pkg has been pushed.
