### ISSUE TITLE
[New Pkg Request]can you upload arduino-cli with 64 bit? thank!

### ISSUE THREAD

**Issue by VirensCn** [jtcmedia/chocolatey-packages#69]
**New Package Requests will only be honored for the $5/month or more Patreon Subscribers.**

* Describe the package that you would like created.
* Provide a link to the software.
can you upload arduino-cli with 64 bit? thank!

**Comment by jtcmedia** [comment]
Thanks for the issue. They added an extra zip and the auto update script wasn't picking up the 64 bit package.  Fixed package version has been released and uploaded to Chocolatey.
