### ISSUE TITLE
TorGuard Package Will Not Install and Has Not Been Updated

### ISSUE THREAD

**Issue by lowcam** [jtcmedia/chocolatey-packages#73]
**Describe the bug**
1) The TorGuard package will not install 

The error is: ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://torguard.net/downloads/new/torguard-setup-latest.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
at Get-WebFile, C:\ProgramData\chocolatey\helpers\functions\Get-WebFile.ps1: line 351
There is more to it than that, but I think that is the main problem that is causing the other errors. If I put that link (https://torguard.net/downloads/new/torguard-setup-latest.exe) into a browser on my system the file downloads.

I ran the following command: choco install torguard-client -debug -verbose

The output from powershell is located at https://gist.github.com/lowcam/64d4ccd7009ba0f39ce3c3918b79442c.

2) The package has not been updated in over 8 months (package version is 4.8.15, current TorGuard version is 4.8.23). 

I believe the reason this package is having these problems is that TorGuard has put their downloads behind Cloudfare's DDOS protection.

**Expected behavior**
1) I expect to be able to install TorGuard. 2) I epect that the package will be updated in a timely fashion to keep up with current TorGuard installations.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
https://gist.github.com/lowcam/64d4ccd7009ba0f39ce3c3918b79442c

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Version: 22H2

**Additional context**
Once again, I think it has to do with TorGuard putting their downloads behind Cloudfare's DDOS protections. I've seen some other packages have problems because of this, I'm not sure if there is a good solution at the moment.

**Comment by jtcmedia** [comment]
Thanks for the info, new pkg has been pushed.
