### ISSUE TITLE
[keepass-plugin-keepassnatmsg] Outdated

### ISSUE THREAD

**Issue by brogers5** [jtcmedia/chocolatey-packages#74]
**Describe the bug**
[v2.0.17](https://github.com/smorks/keepassnatmsg/releases/tag/v2.0.17) has been available for at least 2 days, but a new package has not yet been pushed to the Community Repository.

The update script started to fail for this package as of [this AU run](https://gist.github.com/jtcmedia/8abc37a8c3b020ffdd9704a810331790/a0aafc422ce9466c1d6a38153d40a619cc21fb18#keepass-plugin-keepassnatmsg).

**Expected behavior**
`keepass-plugin-keepassnatmsg` package should update without issues.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by jtcmedia** [comment]
Thanks for bringing this to my attention. For some reason, it failed to install the keepass dependency and then failed to push the updated package. I've pushed it now, should get approved soon.
