### ISSUE TITLE
Zap fails to install using C4B Chocolatey Agent service

### ISSUE THREAD

**Issue by mark-strasser-nnl** [jtcmedia/chocolatey-packages#75]
**Describe the bug**
When using the C4B [`Chocolatey Agent` service](https://docs.chocolatey.org/en-us/agent/), [`chocolateyinstall.ps1` for zap](https://github.com/jtcmedia/chocolatey-packages/blob/master/zap/tools/chocolateyinstall.ps1) aborts indicating the `JAVA_HOME` environment variable is not set.

This occurs because the `chocolatey-agent` service that performs the install runs as `ChocolateyLocalAdmin`, instead of as the calling user.  The calling user's environment is ignored.  When Chocolatey Agent is used, the user does not usually have local administrator rights, so they cannot set a SYSTEM environment variable.

**Expected behavior**
`zap` should install without aborting when using the C4B chocolatey agent "self-service" feature.

**Screenshots**

```
zap v2.14.0
zap package files upgrade completed. Performing other installation steps.
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: JAVA_HOME isn't set. Ensure you set this environment variable to a Java 11+ installation.
The upgrade of zap was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\zap\tools\chocolateyinstall.ps1'.
 See log for details.
```

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Version: 22h2

**Additional context**
I'm willing to contribute a PR, but I would like your feedback first.

Options:
  1. Warn instead of aborting, if JAVA_HOME is not set to a Java 11+ distribution.
  2. If `$env:USER_CONTEXT` is set, assume chocolatey-agent service is running, and look up the value of JAVA_HOME in the calling user's environment as well.
  3. Add a package parameter to either disable the check, or pass a java_home installation location.

**Comment by jtcmedia** [comment]
Thanks for the issue. Not a fan of option 1 or 3 as essentially the pkg can install broken. I like option 2. A PR would be great!
