### ISSUE TITLE
Handbrake v1.8.0+ now requires Microsoft .NET Desktop Runtime 8

### ISSUE THREAD

**Issue by Caligatio** [jtcmedia/chocolatey-packages#79]
**Describe the bug**
I upgraded to Handbrake v1.8.0 via Chocolatey and was prompted to install Microsoft .NET Desktop Runtime 8 on the first run of Handbrake. [Per the Handbrake News](https://handbrake.fr/news.php) page, this is a new requirement with v1.8

**Expected behavior**
The Chocolatey package should include all the prerequisites needed when installing/upgrading a package.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 23H2

**Additional context**
It works fine after installing Microsoft .NET Desktop Runtime .

**Comment by jtcmedia** [comment]
Thanks @Caligatio for letting me know!
